/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hello_Java;

public class App {
    public String getGreeting() {
        return "Hello Java Guillermo Leon";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
